services:
  openbio-cli:
    build: .
    container_name: openbio-cli
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace/openbio
    environment:
      UV_VENV: /workspace/cli/.venv
    env_file:
      - ./.env
    restart: unless-stopped
